### ISSUE TITLE
Unable to compile crtm-tutorial with gcc

### ISSUE THREAD

**Issue by raj879423** [JCSDA/crtm-tutorial#1]
Dear All,

I really need your help to fix this issue, I am handling this issue from last 3 to 4 weeks  almost. 
I have compiled " crtm REL-2.3.0 "successfully and both include and lib also generated completely.

Now the problem is, when i am trying to compile CRTM_TUTORIAL its gives me error in K-Matrix_test & NakajimaKing
This is git file i am using " git clone https://github.com/StegmannJCSDA/CRTM_tutorial"

" I have attached the makefile for K-Matrix_test !! "

$ cat makefile
all:
        gfortran -c -I/home/raj/software/crtm/raj/crtm_gcc/REL-2.3.0/codes/crtm_v2.3.0/include KMatrix_test.f90
        gfortran -L/home/raj/software/crtm/raj/crtm_gcc/REL-2.3.0/codes/crtm_v2.3.0/lib/  -o K.x KMatrix_test.o

clean:
        @rm *.o *.mod

" When i am running make under K-Matrix_test it gives below error.
kindly help me to fix this issue, i am really frustrated with this code and i have to complete soon ."

$ make
gfortran -c -I/home/raj/software/crtm/raj/crtm_gcc/REL-2.3.0/codes/crtm_v2.3.0/include KMatrix_test.f90
gfortran -L/home/raj/software/crtm/raj/crtm_gcc/REL-2.3.0/codes/crtm_v2.3.0/lib/  -o K.x KMatrix_test.o
KMatrix_test.o: In function `MAIN__':
KMatrix_test.f90:(.text+0x1aca): undefined reference to `__crtm_module_MOD_crtm_version'
KMatrix_test.f90:(.text+0x1b83): undefined reference to `__message_handler_MOD_program_message'
KMatrix_test.f90:(.text+0x1eda): undefined reference to `__crtm_lifecycle_MOD_crtm_init'
KMatrix_test.f90:(.text+0x1f9b): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x1fde): undefined reference to `__crtm_channelinfo_define_MOD_crtm_channelinfo_n_channels'
KMatrix_test.f90:(.text+0x4ab0): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x4b22): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_create'
KMatrix_test.f90:(.text+0x4b59): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_associated'
KMatrix_test.f90:(.text+0x4c43): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x4d15): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_create'
KMatrix_test.f90:(.text+0x4db4): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_associated'
KMatrix_test.f90:(.text+0x4ead): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x4f4f): undefined reference to `__crtm_geometry_define_MOD_crtm_geometry_setvalue'
KMatrix_test.f90:(.text+0x4fdf): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_zero'
KMatrix_test.f90:(.text+0x5069): undefined reference to `__crtm_surface_define_MOD_crtm_surface_zero'
KMatrix_test.f90:(.text+0x537d): undefined reference to `__crtm_k_matrix_module_MOD_crtm_k_matrix'
KMatrix_test.f90:(.text+0x543f): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x59f4): undefined reference to `__crtm_lifecycle_MOD_crtm_destroy'
KMatrix_test.f90:(.text+0x5aa8): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x5b41): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_destroy'
KMatrix_test.f90:(.text+0x5b78): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_destroy'
collect2: error: ld returned 1 exit status
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

Thanks on Advance

**Comment by StegmannJCSDA** [comment]
It looks like this issue was fixed with StegmannJCSDA/CRTM_Tutorial#8 and is already fixed in #2. Closing.
